id: I04EB4E01
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T09:11:31+00:00'
last_modified: '2022-06-08T02:24:08.445659+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22203
  title: གསུང་འབུམ། སྐལ་བཟང་ཐུབ་བསྟན་དབང་ཕྱུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    15C6:
      image_group_id: I5195
      title: ''
      total_pages: 1132
      order: 1
      base_file: 15C6.txt
    FECB:
      image_group_id: I5196
      title: ''
      total_pages: 1046
      order: 2
      base_file: FECB.txt
    D4B6:
      image_group_id: I5197
      title: ''
      total_pages: 652
      order: 3
      base_file: D4B6.txt
    4B75:
      image_group_id: I5198
      title: ''
      total_pages: 914
      order: 4
      base_file: 4B75.txt
    ECC9:
      image_group_id: I5199
      title: ''
      total_pages: 586
      order: 5
      base_file: ECC9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
