id: I04EB4E01
legacy_id: P004625
ocr_import_info:
  bdrc_scan_id: W22203
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T09:06:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:59:57.400640+00:00'
last_modified: 2022-09-02 05:01:44.799078
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22203
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22203
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། སྐལ་བཟང་ཐུབ་བསྟན་དབང་ཕྱུག
  author: འཇམ་དབྱངས་བཞད་པ ༠༤་སྐལ་བཟང་ཐུབ་བསྟན་དབང་ཕྱུག
statistics:
  ocr_word_mean_confidence_index: 0.5114845779360269
  ocr_word_median_confidence_index: 0.47999998927116394
quality: null
bases:
  I5197:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5197
      total_pages: 652
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I5197.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5241789794119678
    legacy_id: v003
  I5198:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5198
      total_pages: 914
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I5198.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5162969347883477
    legacy_id: v004
  I5195:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5195
      total_pages: 1132
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5195.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.49702443631016785
    legacy_id: v001
  I5196:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5196
      total_pages: 1046
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5196.txt
    statistics:
      ocr_word_median_confidence_index: 0.46000000834465027
      ocr_word_mean_confidence_index: 0.49092357641100887
    legacy_id: v002
  I5199:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5199
      total_pages: 586
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I5199.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5508418027492779
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
